<h2 class="sub-header">Proyectos</h2>
<a href="?action=insert">Insertar proyecto</a>
<br/>
<table class="table table-striped">
<?php foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>
		<td>
			<a href="?action=update&idproject=<?=$fila['idproject'];?>">Update</a>
				&nbsp;
			<a href="?action=delete&idproject=<?=$fila['idproject'];?>">Delete</a>
		</td>
	</tr>
<?php endforeach ?>
</table>